language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src
install:
- pip install -U platformio
- platformio lib -g install WifiManager
- platformio lib -g install NeoPixelBus
- platformio lib -g install ArduinoJson
script:
- mkdir upload
- platformio ci --board=nodemcuv2
- cp .pioenvs/nodemcuv2/firmware.bin upload/esp8266.bin
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: uU/egrmZP3a09SAA7JlHdAeQP3veWRKydQZyF1QiBdGGcbwyJjx/bg91V4vq1ol2nZJk8WRMNTYFhxITI8o5Jo5EPwEw7VBUQitw+geiRwwTXWzRGldrUHcOpbdqSbo6b8EjQd1mT7Hia7K3WHDtynKH8ePKK0Pci2wAIp/c7rEJQuMES7NSLl19JSu23zXu6OduF6r5MyXWVe7ZFaGLC/cjAGvrmTmBnmTI9it4iIuNizIQFF6lttnl08aJckAbuJUMlfNpFMfz4xtSMZRdwA5ZIgOS8I40vQAJJnhOHVxJ3Xq1z+B97GoUcV85vzt0WwEVZJgbgI3dLHR0oLuH7uYdjlFx/Wv2wsgKLfLlOHmAVTnkqmer9JNy/mMt65QA7/SOT3cgJ5TbgbtCMc0D3ggVxG8n1zlMui3GLFlrCXiSF663/JpxsO6TId7COsTOUHSb29EHiDhydb6YY1L16aHx+8QqFMbQ9+aGXpG4opKh26vp/ULjLhoUU9zsbGxlnDvveji1fHHYi1Xc1Xxr7N+F/1zbS3DCBy9VXtVZatRMUv4x8bsWH1anrYbm1GG5LWt78SkylcJbN4nfI6ST8f+et2QdyJFlcDuxfba5bjocxaZpyBd4kzIUS+lv134ONt8zwkbTvVteHR3Vi6fORCzd45cZxs+sPQHN0NkO1kY=
  secret_access_key:
    secure: 05TKrC2T9c+ffp4UtIB3TB1nUVzYfK0QwsgujXWCH7DjOtuGTJXg7bwtUKAAknKJV3bfNn9YP9nuewF6k1b+IqI/W+GpGhb43Crt5JhqeDD7ljmdBIrNBOHnoO1vuoHlGZLMHDaTkGiC5pmNqZ+TJVV3qJGknr3MhpWYE89uNvOq4Yx0ecGbXKj/PrUEpiW1ZU/VunM7GkTvZpCI9dQojelqL0ZuCabrKzvPY6U6Fy7vRNMuOGVDeWsqTR/brLZXttKd8YUgz+4P/8OSyC5fo48HYPSoGiDQN37r/rcmtK19r6/W3IR8kcAnHK8f2lNy91eGQmJThQOHZeNRZX7CTVrCm+3IUorjevHPQUbMsHX+IQ4VyuDJ34Q7ziGoYij5o4vpvi52TOsYbZzmuTqCnzN+e4pWXkT+i8wEu+87eY2x+wJZcn1dCqNNxGhHlm1qQT41ktZ4Man7osMRuvXgLk6CpM4jUvBh6Ckwe1xXUIVMxg/Q2x7wdW8Q6ABExvfWcw2sDhIPpxBQuMRa8cbMibOUjZFUJB8WL/bzg9Q6pQGyd3rGom0SAZLR9I89zltcwjy4VAKb6l+Gml1ZwqBFeSrGNwSZ02oUEXYuBgfULiWpKtcjgkU0ND+au4sh5UhUSrMMot0MGX1EsyEYN1VrTRm+ZAI9Y2DUQx9HApi69E8=
  bucket: antroids-webstrip
  upload-dir: firmware
  file: upload/esp8266.bin
